-- SQLite
-- TABELA DE CARROS
CREATE TABLE CARS (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  NAME VARCHAR(120) NOT NULL,
  YEAR INTEGER NOT NULL,
  COLOR VARCHAR(32),
  KM FLOAT(10,2) NOT NULL,
  STATUS VARCHAR(17) NOT NULL,
  CAR_BRAND_ID INTEGER NOT NULL,
  CAR_MODEL_ID INTEGER NOT NULL,

  FOREIGN KEY (CAR_BRAND_ID) REFERENCES CAR_BRANDS (ID),
  FOREIGN KEY (CAR_MODEL_ID) REFERENCES CAR_MODELS (ID)
);

DROP TABLE CARS;